experiments/urls.py
try:
    from django.conf.urls import patterns, url
except ImportError:  # django < 1.4
    from django.conf.urls.defaults import patterns, url

urlpatterns = patterns('experiments.views',
    url(r'^goal/(?P<goal_name>[^/]+)/(?P<cache_buster>[^/]+)?$', 'record_experiment_goal', name="experiment_goal"),
    url(r'^confirm_human/$', 'confirm_human', name="experiment_confirm_human"),
    url(r'^change_alternative/(?P<experiment_name>[a-zA-Z0-9-_]+)/(?P<alternative_name>[a-zA-Z0-9-_]+)/$', 'change_alternative', name="experiment_change_alternative"),
)

experiments/models.py
from django.core.urlresolvers import reverse
from django.db import models
from django.core.serializers.json import DjangoJSONEncoder
from django.conf import settings

from jsonfield import JSONField

from gargoyle.manager import gargoyle
from gargoyle.models import Switch

import random
import json

from experiments import conf
from experiments.dateutils import now


CONTROL_STATE = 0
ENABLED_STATE = 1
GARGOYLE_STATE = 2
TRACK_STATE = 3

STATES = (
    (CONTROL_STATE, 'Control'),
    (ENABLED_STATE, 'Enabled'),
    (GARGOYLE_STATE, 'Gargoyle'),
    (TRACK_STATE, 'Track'),
)


class Experiment(models.Model):
    name = models.CharField(primary_key=True, max_length=128)
    description = models.TextField(default="", blank=True, null=True)
    alternatives = JSONField(default={}, blank=True)
    relevant_chi2_goals = models.TextField(default="", null=True, blank=True)
    relevant_mwu_goals = models.TextField(default="", null=True, blank=True)
    switch_key = models.CharField(default="", max_length=50, null=True, blank=True)

    state = models.IntegerField(default=CONTROL_STATE, choices=STATES)

    start_date = models.DateTimeField(default=now, blank=True, null=True, db_index=True)
    end_date = models.DateTimeField(blank=True, null=True)

    def is_displaying_alternatives(self):
        if self.state == CONTROL_STATE:
            return False
        elif self.state == ENABLED_STATE:
            return True
        elif self.state == GARGOYLE_STATE:
            return True
        elif self.state == TRACK_STATE:
            return True
        else:
            raise Exception("Invalid experiment state %s!" % self.state)

    def is_accepting_new_users(self, request):
        if self.state == CONTROL_STATE:
            return False
        elif self.state == ENABLED_STATE:
            return True
        elif self.state == GARGOYLE_STATE:
            return gargoyle.is_active(self.switch_key, request)
        elif self.state == TRACK_STATE:
            return False
        else:
            raise Exception("Invalid experiment state %s!" % self.state)

    def ensure_alternative_exists(self, alternative, weight=None):
        if alternative not in self.alternatives:
            self.alternatives[alternative] = {}
            self.alternatives[alternative]['enabled'] = True
            self.save()
        if weight is not None and 'weight' not in self.alternatives[alternative]:
            self.alternatives[alternative]['weight'] = float(weight)
            self.save()

    def random_alternative(self):
        if all('weight' in alt for alt in self.alternatives.values()):
            return weighted_choice([(name, details['weight']) for name, details in self.alternatives.items()])
        else:
            return random.choice(self.alternatives.keys())

    def __unicode__(self):
        return self.name

    def to_dict(self):
        data = {
            'name': self.name,
            'edit_url': reverse('experiments:results', kwargs={'name': self.name}),
            'start_date': self.start_date,
            'end_date': self.end_date,
            'state': self.state,
            'switch_key': self.switch_key,
            'description': self.description,
            'relevant_chi2_goals': self.relevant_chi2_goals,
            'relevant_mwu_goals': self.relevant_mwu_goals,
        }
        return data

    def to_dict_serialized(self):
        return json.dumps(self.to_dict(), cls=DjangoJSONEncoder)

    def save(self, *args, **kwargs):
        # Create new switch
        if self.switch_key and conf.SWITCH_AUTO_CREATE:
            try:
                Switch.objects.get(key=self.switch_key)
            except Switch.DoesNotExist:
                Switch.objects.create(key=self.switch_key, label=conf.SWITCH_LABEL % self.name, description=self.description)

        if not self.switch_key and self.state == 2:
            self.state = 0

        super(Experiment, self).save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        # Delete existing switch
        if conf.SWITCH_AUTO_DELETE:
            try:
                Switch.objects.get(key=Experiment.objects.get(name=self.name).switch_key).delete()
            except Switch.DoesNotExist:
                pass

        super(Experiment, self).delete(*args, **kwargs)


class Enrollment(models.Model):
    """ A participant in a split testing experiment """
    user = models.ForeignKey(getattr(settings, 'AUTH_USER_MODEL', 'auth.User'), null=True)
    experiment = models.ForeignKey(Experiment)
    enrollment_date = models.DateTimeField(auto_now_add=True)
    last_seen = models.DateTimeField(null=True)
    alternative = models.CharField(max_length=50)

    class Meta:
        unique_together = ('user', 'experiment')

    def __unicode__(self):
        return u'%s - %s' % (self.user, self.experiment)

    def to_dict(self):
        data = {
            'user': self.user,
            'experiment': self.experiment,
            'enrollment_date': self.enrollment_date,
            'alternative': self.alternative,
            'goals': self.goals,
        }
        return data


def weighted_choice(choices):
    total = sum(w for c, w in choices)
    r = random.uniform(0, total)
    upto = 0
    for c, w in choices:
        upto += w
        if upto >= r:
            return c

experiments/views.py
from django.http import HttpResponse, HttpResponseBadRequest
from django.views.decorators.cache import never_cache
from django.shortcuts import get_object_or_404
from django.views.decorators.http import require_POST

from experiments.utils import participant, record_goal
from experiments import record_goal
from experiments.models import Experiment

TRANSPARENT_1X1_PNG = \
("\x89\x50\x4e\x47\x0d\x0a\x1a\x0a\x00\x00\x00\x0d\x49\x48\x44\x52"
 "\x00\x00\x00\x01\x00\x00\x00\x01\x08\x03\x00\x00\x00\x28\xcb\x34"
 "\xbb\x00\x00\x00\x19\x74\x45\x58\x74\x53\x6f\x66\x74\x77\x61\x72"
 "\x65\x00\x41\x64\x6f\x62\x65\x20\x49\x6d\x61\x67\x65\x52\x65\x61"
 "\x64\x79\x71\xc9\x65\x3c\x00\x00\x00\x06\x50\x4c\x54\x45\x00\x00"
 "\x00\x00\x00\x00\xa5\x67\xb9\xcf\x00\x00\x00\x01\x74\x52\x4e\x53"
 "\x00\x40\xe6\xd8\x66\x00\x00\x00\x0c\x49\x44\x41\x54\x78\xda\x62"
 "\x60\x00\x08\x30\x00\x00\x02\x00\x01\x4f\x6d\x59\xe1\x00\x00\x00"
 "\x00\x49\x45\x4e\x44\xae\x42\x60\x82\x00")


@never_cache
@require_POST
def confirm_human(request):
    experiment_user = participant(request)
    experiment_user.confirm_human()
    return HttpResponse(status=204)


@never_cache
def record_experiment_goal(request, goal_name, cache_buster=None):
    record_goal(goal_name, request)
    return HttpResponse(TRANSPARENT_1X1_PNG, mimetype="image/png")


def change_alternative(request, experiment_name, alternative_name):
    experiment = get_object_or_404(Experiment, name=experiment_name)
    if alternative_name not in experiment.alternatives.keys():
        return HttpResponseBadRequest()

    participant(request).set_alternative(experiment_name, alternative_name)
    return HttpResponse('OK')

experiments/templates/experiments/confirm_human.html
{% if not request.session.experiments_verified_human %}
    <script type="text/javascript" charset="utf-8">
        experiments.confirm_human();
    </script>
{% endif %}

experiments/templates/experiments/goal.html
<img src="{{ url }}" height="1" width="1" />

experiments/templates/nexus/experiments/dashboard.html
{% load url from future %}
{% if not enabled_experiments %}
    <p>There are no active experiments.</p>
{% else %}    
    <p>There are <b>{{ enabled_experiments_count }} active</b> experiments.</p>
    <table class="experiment-list">
        {% for experiment in enabled_experiments %}
            <tr>
                <td><a href="{% url 'experiments:results' experiment.name %}">{{experiment.name}}</a></td>
            </tr>
        {% endfor %}
    </table>
{% endif %}

experiments/templates/nexus/experiments/index.html
{% extends "nexus/module.html" %}

{% load experiment_helpers %}
{% load url from future %}

{% block head %}
    {{ block.super }}

    <link rel="stylesheet" href="{% url 'nexus:media' 'experiments' 'css/experiments.css' %}">

    <style>
        #container table.experiments td.actions button.edit span {
            background: transparent url("{% url 'nexus:media' 'experiments' 'img/edit.png' %}") no-repeat left 35%;
        }

        #container table.experiments td.actions button.delete span {
            background: transparent url("{% url 'nexus:media' 'experiments' 'img/delete.png' %}") no-repeat left 35%;
        }
    </style>

    <script>
        var EXPERIMENT = {
            addExperiment:    "{% url 'experiments:add' %}",
            updateExperiment: "{% url 'experiments:update' %}",
            deleteExperiment: "{% url 'experiments:delete' %}",
            updateState:      "{% url 'experiments:state' %}",
        };
        nexus_experiments_all_goals = {{ all_goals|safe }};
    </script>

    <script src="{% url 'nexus:media' 'experiments' 'js/string_score.min.js' %}"></script>
    <script src="{% url 'nexus:media' 'experiments' 'js/nexus_experiments.js' %}"></script>
{% endblock %}

{% block content %}
    <div class="toolbar" data-sort="{{ sorted_by }}">
        {% if perms.experiments.add_experiment %}
            <button class="button addExperiment">Add an Experiment</button>
        {%  endif %}

        <span class="search">
            <input type="text" placeholder="search">
        </span>

        <ul class="sort">
            <li class="start_date">
                <a href="?by={{'start_date'|sort_by_key:sorted_by}}">Start Date</a>
            </li>
            <li class="end_date">
                <a href="?by={{'end_date'|sort_by_key:sorted_by}}">End Date</a>
            </li>  
            <li class="name">
                <a href="?by={{'name'|sort_by_key:sorted_by}}">Name</a>
            </li>          
        </ul>

    </div>

    <div class="noExperiments" {% if experiments %}style="display:none;"{% endif %}>
        You do not have any experiments.
    </div>

    <table class="experiments {% if not experiments %}empty{% endif %}">
        {% for experiment in experiments %}
        <tr data-experiment-name="{{ experiment.name }}" data-experiment-switch="{{ experiment.switch_key }}" data-experiment-desc="{{ experiment.description }}" data-experiment-chi2-goals="{{ experiment.relevant_chi2_goals }}" data-experiment-mwu-goals="{{ experiment.relevant_mwu_goals }}" class="collapsed">
            <td class="name">
                <h4>{{ experiment.name }}
                <a href="{% url 'experiments:results' experiment.name %}">(View Results)</a>
                    <small>
                        <span id = "{{ experiment.name }}_start_date"
                            {% if experiment.start_date %}
                                 >Started: {{ experiment.start_date }}
                            {% else %}
                                style="display:none;">Started: 
                            {% endif %}
                        </span>
                        <span id = "{{ experiment.name }}_end_date"
                            {% if experiment.end_date %}
                                >Ended: {{ experiment.end_date }}
                            {% else %}
                                style="display:none;">Ended: 
                            {% endif %}
                        </span>
                    </small>
                </h4>

                <div class="inner">
                    {% if experiment.description %}
                        <p>{{ experiment.description }}</p>
                    {% endif %}

                    {% if experiment.switch_key %}
                        <p>Connected to Gargoyle switch <a href="{% url 'gargoyle:index' %}#id_{{ experiment.switch_key }}">{{ experiment.switch_key }}</a>.</p>
                    {% endif %}
                </div>

            </td>

            <td class="state">
                <div data-experiment-name="{{experiment.name}}" class="state">
                    <button class="xtrasmall button {% if experiment.state == 3 %}toggled{% endif %}" data-state="3">
                        Track
                    </button>

                    <button class="xtrasmall button {% if experiment.state == 2 %}toggled{% endif %}" data-state="2" {% if not experiment.switch_key %}disabled="disabled"s{% endif %}>
                        Gargoyle
                    </button>

                    <button class="xtrasmall button {% if experiment.state == 1 %}toggled{% endif %}" data-state="1">
                        Enabled
                    </button>

                    <button class="xtrasmall button {% if experiment.state == 0 %}toggled{% endif %}" data-state="0">
                        Control
                    </button>
                </div>
            </td>

            <td class="actions">
                {% if perms.experiments.change_experiment %}
                    <button class="edit xtrasmall button"><span></span></button>
                {% endif %}
                {% if perms.experiments.delete_experiment %}
                    <button class="delete xtrasmall button"><span></span></button>
                {%  endif %}
            </td>
        </tr>
        {% endfor %}
    </table>
    {% raw %}
        <script type="text/x-jquery-tmpl" id="experimentForm">
            {{ if add }}
                <h2>Add an Experiment</h2>
            {{ else }}
                <h2>Update an Experiment</h2>
            {{ /if }}

            <table class="experimentForm">
                <tr>
                    <th>Name:</th>
                    <td>
                        <input name="name" type="text" value="{{ if name }}${name}{{ /if }}" {{ if add }}{{ else }}disabled{{ /if }}>
                        <p>The experiment name.</p>
                    </td>
                </tr>
                <tr>
                    <th>Switch Key:</th>
                    <td>
                        <input name="switch_key" type="text" value="{{ if switch_key }}${switch_key}{{ /if }}">
                        <p>Connected gargoyle switch. (Optional)</p>
                    </td>
                </tr>
                <tr>
                    <th>Description:</th>
                    <td>
                        <textarea name="desc">{{ if desc }}${desc}{{ /if }}</textarea>
                        <p>A brief description of this experiment.</p>
                    </td>
                </tr>
                <tr>
                    <th>Relevant Goals:</th>
                    <td>
                        <div class="select-list-header">
                            <div class="label-header">Goal</div>
                            <div class="checkbox-header">
                                <a href="http://en.wikipedia.org/wiki/Chi-squared_test" target="_blank" title="Used when optimising for conversion rate">&Chi;&sup2;</a>
                            </div>
                            <div class="checkbox-header">
                                <a href="http://en.wikipedia.org/wiki/Mann%E2%80%93Whitney_U" target="_blank" title="Used when optimising for number of times users perform an action. (Advanced.)">U</a>
                            </div>
                        </div>
                        <div class="select-list-container">
                            {{each all_goals}}
                                <label>${$value}</label>
                                 <input type="checkbox" name="relevant_chi2_goals" value="${$value}" {{if relevant_chi2_goals.indexOf($value)>-1 }}checked{{/if}}>
                                <input type="checkbox" name="relevant_mwu_goals" value="${$value}" {{if relevant_mwu_goals.indexOf($value)>-1 }}checked{{/if}}>
                            {{/each}}
                        </div>
                        <p>Comma separated list of relevant goals.</p>
                    </td>
                </tr>
                <tr>
                    <td colspan="2" class="buttons">
                        <button
                            data-action="{{ if add }}add{{ else }}update{{ /if }}"
                            data-curname="${curname}"
                            class="submitExperiment small button">{{ if add }}Add{{ else }}Update{{ /if }}</button>
                        or <a href="#" class="closeFacebox">cancel</a>
                    </td>
                </tr>
            </table>
        </script>
        <script type="text/x-jquery-tmpl" id="experimentData">
            <tr data-experiment-name="${name}" data-experiment-switch="${switch_key}" data-experiment-desc="${description}" data-experiment-chi2-goals="${relevant_chi2_goals}" data-experiment-mwu-goals="${relevant_mwu_goals}">
                <td class="name">
                    <h4>
                        ${name}

                        <a href="${edit_url}">(View Results)</a>

                        <small>
                            {{if start_date }}Started: ${start_date}{{/if}}
                            {{if end_date }} Ended: ${end_date}{{/if}}
                        </small>
                    </h4>
                    
                    <div class="inner">
                        {{ if description }}
                            <p>${description}</p>
                        {{ /if }}

                        {{ if switch_key }}
                            <p>Connected to Gargoyle switch <a href="{% endraw %}{% url 'gargoyle:index' %}{% raw %}#id_${switch_key}">${switch_key}</a>.</p>
                        {{ /if }}
                    </div>
                </td>

                <td class="state">
                    <div class = "state" data-experiment-name="${name}">
                        <button class="xtrasmall button {{if state == 3}}toggled{{/if}}" data-state="3">
                            Track
                        </button>

                        <button class="xtrasmall button {{if state == 2}}toggled{{/if}}" data-state="2" {{ if !switch_key }}disabled="disabled"{{ /if }}>
                            Gargoyle
                        </button>

                        <button class="xtrasmall button {{if state == 1}}toggled{{/if}}" data-state="1">
                            Enabled
                        </button>
                        <button class="xtrasmall button {{if state == 0}}toggled{{/if}}" data-state="0">
                            Control
                        </button>
                    </div>
                </td>

                {% endraw %}
                <td class="actions">
                    {% if perms.experiments.change_experiment %}
                        <button class="edit xtrasmall button"><span></span></button>
                    {% endif %}
                    {% if perms.experiments.delete_experiment %}
                        <button class="delete xtrasmall button"><span></span></button>
                    {%  endif %}
                </td>
                {% raw %}
            </tr>
        </script>

    {% endraw %}

{% endblock %}

experiments/templates/nexus/experiments/results.html
{% extends "nexus/module.html" %}
{% load humanize %}
{% load experiment_helpers %}
{% load url from future %}

{% block head %}
    {{ block.super }}

    <link rel="stylesheet" href="{% url 'nexus:media' 'experiments' 'css/experiments.css' %}">

    <script>
        var EXPERIMENT = {
            addExperiment:    "{% url 'experiments:add' %}",
            updateExperiment: "{% url 'experiments:update' %}",
            deleteExperiment: "{% url 'experiments:delete' %}",
            updateState:      "{% url 'experiments:state' %}",
            setAlternative:   "{% url 'experiments:set_alternative' %}",

        };

        EXPERIMENT_CHART_DATA = {};
    </script>


    <script type="text/javascript" src="https://www.google.com/jsapi"></script>
    <script type="text/javascript">
      google.load('visualization', '1.0', {'packages':['corechart']});
    </script>

    <script src="{% url 'nexus:media' 'experiments' 'js/nexus_experiments.js' %}"></script>

{% endblock %}

{% block content %}
    <div class="results header top">
        <h2 class="experiment">{{ experiment.name }}</h2>
        <div data-experiment-name="{{experiment.name}}" class="results state">
            <button class="xtrasmall button {% if experiment.state == 3 %}toggled{% endif %}" data-state="3">
                Track
            </button>

            <button class="xtrasmall button {% if experiment.state == 2 %}toggled{% endif %}" data-state="2" {% if not experiment.switch_key %}disabled="disabled"{% endif %}>
                Gargoyle
            </button>

            <button class="xtrasmall button {% if experiment.state == 1 %}toggled{% endif %}" data-state="1">
                Enabled
            </button>

            <button class="xtrasmall button {% if experiment.state == 0 %}toggled{% endif %}" data-state="0">
                Control
            </button>
        </div>
    </div>

    {% if experiment.switch_key %}
        <div data-experiment-name="{{experiment.name}}" class="results header" style>
            Connected to Gargoyle switch <a href="{% url 'gargoyle:index' %}#id_{{experiment.switch_key}}">{{experiment.switch_key}}</a>.
        </div>
    {% endif %}

    <div class="results header bottom">
        {% if experiment.description %}<p>{{ experiment.description }}</p>{% endif %}

        <div class="dates">
            <div id = "{{ experiment.name }}_start_date"
                {% if experiment.start_date %}
                     >Started: {{ experiment.start_date }}
                {% else %}
                    style="display:none;">Started: 
                {% endif %}
            </div>
            <div id = "{{ experiment.name }}_end_date"
                {% if experiment.end_date %}
                    >Ended: {{ experiment.end_date }}
                {% else %}
                    style="display:none;">Ended: 
                {% endif %}
            </div>
        </div>
    </div>
        
    <table class="goals{% if not results %}empty{% endif %}">

        <thead>
            <tr>
                <td class="goal odd"></td>
                <td class="conversion1 even">
                    control <small>({{ control_participants|intcomma }})</small>
                    <div class="enrollment-indicator" data-experiment="{{ experiment.name }}" data-alternative="control">
                        {% if user_alternative == 'control' %}
                            Enrolled
                        {% else %}
                            <a href="#" class="js-join-alternative">Join</a>
                        {% endif %}
                    </div>
                </td>
                {% for alternative, participants in alternatives %}
                     {% if alternative != 'control' %}
                         <td colspan="3" class="conversion2 {% if forloop.counter|divisibleby:2 %}odd{% else %}even{% endif %}">
                            {{ alternative }} <small>({{ participants|intcomma }})</small>
                            <div class="enrollment-indicator" data-experiment="{{ experiment.name }}" data-alternative="{{ alternative }}">
                                {% if user_alternative == alternative %}
                                    Enrolled
                                {% else %}
                                    <a href="#" class="js-join-alternative">Join</a>
                                {% endif %}
                            </div>
                         </td>
                     {% endif %}
                {% endfor %}
            </tr>
        </thead>

        <tbody>
            {% for goal, data in results.items %}
                <tr id="{{goal}}-row" class="row-{% cycle 'odd' 'even' %} {% if not data.relevant %}hiddengoal{% endif %}">

                    <td class="goal odd">
                        {% if data.mwu %}
                            <a href="#" class="toggle_chart" data-element-id="{{ goal }}_chart">{{ goal }}</a>
                        {% else %}
                            {{ goal }}
                        {% endif %}
                    </td>

                    <td class="conversion1 even">
                        {{ data.control.conversions|intcomma }} <small>({{ data.control.conversion_rate|floatformat:2 }}%
                        {% if data.mwu %}
                        - APU {{ data.control.average_goal_actions|floatformat:2 }}
                        {% endif %}
                        )</small></td>

                    {% for alternative_name, results in data.alternatives %}
                        {% if alternative_name != 'control' %}
                            <td class="conversion2 {% if forloop.counter|divisibleby:2 %}even{% else %}odd{% endif %}">
                                {{ results.conversions|intcomma }}<small> ({{ results.conversion_rate|floatformat:2 }}%
                                {% if data.mwu %}
                                    - APU {{ results.average_goal_actions|floatformat:2 }}
                                {% endif %}
                                )</small>
                            </td>
                            <td title="Improvement" class="improvement {% if forloop.counter|divisibleby:2 %}odd{% else %}even{% endif %}">
                                {% with improvement=results.improvement confidence=results.confidence %}
                                    {% if improvement != None %}
                                        {% if confidence >= 95 and improvement < 0 %}
                                            <span class="negative_improvement">
                                        {% elif confidence >= 95 and improvement > 0 %}
                                            <span class="positive_improvement">
                                        {% else %}
                                            <span>
                                        {% endif %}
                                        {{ improvement|floatformat:2 }} %</span>
                                    {% else %}
                                        N/A
                                    {% endif %}
                                {% endwith %}
                            </td>
                            <td title="Confidence Interval" class="confidence_interval {% if forloop.counter|divisibleby:2 %}even{% else %}odd{% endif %}">
                                {% with results.confidence as confidence %}
                                    {% if confidence != None %}
                                        {% if confidence >= 95 %}
                                            <span class="high_confidence">
                                        {% endif %}
                                        {% if confidence < 95 %}
                                            <span class="low_confidence">
                                        {% endif %}
                                        {% if confidence >= 99.995 %}
                                            ~{{ confidence|floatformat:2 }} %
                                        {% else %}
                                            {{ confidence|floatformat:2 }} %
                                        {% endif %}
                                        </span>
                                    {% else %}
                                        N/A
                                    {% endif %}
                                {% endwith %}
                                {% if data.mwu %}
                                    MWU: {{ results.mann_whitney_confidence|floatformat:2 }}%
                                {% endif %}
                            </td>
                        {% endif %}
                    {% endfor %}
                </tr>
                {% if data.mwu %}
                    <tr class="row-{% cycle 'odd' 'even' %}" id="{{goal}}_mwu_row">
                        <td class="chart" colspan="{{ column_count }}" >
                            <div id="{{goal}}_chart" data-chart-key="{{goal}}" data-rendered="0"></div>
                            <script type="text/javascript">
                                EXPERIMENT_CHART_DATA['{{goal|escapejs}}'] = {{ data.mwu_histogram|safe }};
                            </script>

                        </td>
                    </tr>
                {% endif %}
            {% endfor %}
        </tbody>
    </table>

    <a id  = "ToggleGoals" href="#">Toggle All Goals</a>

{% endblock content %}